## server
server:
  port: 8081

## spring
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512

## logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  level:
    root: info
    web: debug
    com:
      example: debug
