## server
server:
  port: 8081

## spring
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
#          introspection-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token/introspect
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: oauth2-client-app
          client-secret: secret

## logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  level:
    root: info
    web: debug
    com.example: debug
